### PR TITLE
Add role to read this repo's Terraform state

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##
This PR creates a role that allows read-only access to the shared Terraform state for this repository, which resides in our S3 bucket in the Terraform account).

It also creates a policy in the Users account that allows the role above to be assumed.

## 💭 Motivation and context ##
This PR mirrors changes that were made in https://github.com/cisagov/cool-sharedservices-networking/pull/41, as we have realized that it makes the most sense to house the Terraform for this role and policy in this repository.

## 🧪 Testing ##

This change was successfully Terraformed in Staging. All pre-commit hooks pass.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [x] All new and existing tests pass.

## ✅ Post-Merge Checklist ##
* [ ] Apply changes to Production workspace.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
As a future improvement, I think it is worth considering the creation of a Terraform module that creates the read-only role for an account.  Let me know if you agree, and if so let's create an issue for that.

**Comment by dav3r** [comment]
> As a future improvement, I think it is worth considering the creation of a Terraform module that creates the read-only role for an account. Let me know if you agree, and if so let's create an issue for that.

Yes, I think that's a good idea.  Should it also create the policy to allow assumption of the read-only role?

**Comment by jsf9k** [comment]
> > As a future improvement, I think it is worth considering the creation of a Terraform module that creates the read-only role for an account. Let me know if you agree, and if so let's create an issue for that.
> 
> Yes, I think that's a good idea. Should it also create the policy to allow assumption of the read-only role?

Yes, unless you have a good reason why it shouldn't.  The idea is to DRY this out.

**Review by hillaryj — APPROVED** [review]
💪🏻

**Comment by dav3r** [comment]
> > > As a future improvement, I think it is worth considering the creation of a Terraform module that creates the read-only role for an account. Let me know if you agree, and if so let's create an issue for that.
> > 
> > 
> > Yes, I think that's a good idea. Should it also create the policy to allow assumption of the read-only role?
> 
> Yes, unless you have a good reason why it shouldn't. The idea is to DRY this out.

Issue created for this:  https://github.com/cisagov/cool-system/issues/177

**Pull request merged**
